export interface Tip {
  en: string;
  ko: string;
  ja: string;
}

export const TIPS: Tip[] = [
  // 1-50: Core Sino-Korean / Sino-Japanese identical vocabulary (school/education)
  { en: "The word for 'school' is 학교 (hak-gyo) in Korean and 学校 (gakkō) in Japanese — both written with the same Chinese characters 學校.", ko: "학교(學校)는 한국어와 일본어에서 같은 한자를 씁니다. 발음만 다를 뿐이에요!", ja: "「学校」は韓国語で학교(ハッキョ)、日本語でがっこう。同じ漢字を使います！" },
  { en: "'Library' is 도서관 (do-seo-gwan) in Korean and 図書館 (toshokan) in Japanese — the same three characters 圖書館.", ko: "도서관(圖書館)은 일본어로 としょかん(図書館). 한자가 똑같아요!", ja: "図書館は韓国語で도서관(トソグァン)。三つの漢字が完全に一致します。" },
  { en: "'Mathematics' is 수학 (su-hak) in Korean and 数学 (sūgaku) in Japanese — both from the characters 數學.", ko: "수학(數學)은 일본어로 すうがく. 같은 한자에서 온 단어예요.", ja: "数学は韓国語で수학(スハク)。どちらも同じ漢字由来です。" },
  { en: "'Science' is 과학 (gwa-hak) in Korean and 科学 (kagaku) in Japanese — characters 科學.", ko: "과학(科學)은 일본어로 かがく(科学). 발음은 달라도 뜻은 같아요.", ja: "科学は韓국語で과학(クァハク)。文字は同じ、発音が違います。" },
  { en: "'History' is 역사 (yeok-sa) in Korean and 歴史 (rekishi) in Japanese — both from 歷史.", ko: "역사(歷史)는 일본어로 れきし(歴史). 같은 한자 기반이에요.", ja: "歴史は韓国語で역사(ヨクサ)。同じ漢字から来ています。" },
  { en: "'Student' is 학생 (hak-saeng) in Korean and 学生 (gakusei) in Japanese — characters 學生.", ko: "학생(學生)은 일본어로 がくせい(学生). 둘 다 같은 한자예요!", ja: "学生は韓国語で학생(ハクセン)。漢字が同一です！" },
  { en: "'Teacher' is 교사 (gyo-sa) in Korean and 教師 (kyōshi) in Japanese — from 教師.", ko: "교사(教師)는 일본어로 きょうし(教師). 한자가 동일해요.", ja: "教師は韓国語で교사(キョサ)。同じ漢字です。" },
  { en: "'University' is 대학교 (dae-hak-gyo) in Korean and 大学 (daigaku) in Japanese — from 大學.", ko: "대학교(大學校)는 일본어로 だいがく(大学). 같은 한자 조합이에요.", ja: "大学は韓国語で대학교(テハッキョ)。漢字の組み合わせが似ています。" },
  { en: "'Homework' is 숙제 (suk-je) in Korean and 宿題 (shukudai) in Japanese — from 宿題.", ko: "숙제(宿題)는 일본어로 しゅくだい(宿題). 한자까지 동일해요!", ja: "宿題は韓国語で숙제(スクチェ)。漢字もまったく同じです！" },
  { en: "'Test/exam' is 시험 (si-heom) in Korean and 試験 (shiken) in Japanese — from 試驗.", ko: "시험(試驗)은 일본어로 しけん(試験). 같은 한자에서 왔어요.", ja: "試験は韓国語で시험(シホム)。同じ漢字由来です。" },
  { en: "'Question' is 질문 (jil-mun) in Korean and 質問 (shitsumon) in Japanese — from 質問.", ko: "질문(質問)은 일본어로 しつもん(質問). 발음은 달라도 한자는 같아요.", ja: "質問は韓国語で질문(チルムン)。漢字は一致しています。" },
  { en: "'Answer' is 답변 (dap-byeon) in Korean and 答弁 (tōben) in Japanese, or 回答 (kaitō) — all share Chinese character roots.", ko: "답변(答辯)과 일본어 とうべん(答弁)은 같은 한자 기반이에요.", ja: "答弁は韓国語で답변(タッピョン)。漢字の根が同じです。" },
  { en: "'Class/lesson' is 수업 (su-eop) in Korean and 授業 (jugyō) in Japanese — from 授業.", ko: "수업(授業)은 일본어로 じゅぎょう(授業). 한자가 똑같아요!", ja: "授業は韓国語で수업(スオプ)。漢字が完全一致です！" },
  { en: "'Graduation' is 졸업 (jol-eop) in Korean and 卒業 (sotsugyō) in Japanese — from 卒業.", ko: "졸업(卒業)은 일본어로 そつぎょう(卒業). 같은 한자예요.", ja: "卒業は韓国語で졸업(チョロプ)。同じ漢字です。" },
  { en: "'Research' is 연구 (yeon-gu) in Korean and 研究 (kenkyū) in Japanese — from 硏究.", ko: "연구(硏究)는 일본어로 けんきゅう(研究). 발음이 비슷해요!", ja: "研究は韓国語で연구(ヨング)。発音も似ています！" },
  { en: "'Dictionary' is 사전 (sa-jeon) in Korean and 辞典 (jiten) in Japanese — from 辭典.", ko: "사전(辭典)은 일본어로 じてん(辞典). 같은 한자 기반이에요.", ja: "辞典は韓국語で사전(サジョン)。同じ漢字由来です。" },
  { en: "'Textbook' is 교과서 (gyo-gwa-seo) in Korean and 教科書 (kyōkasho) in Japanese — from 教科書.", ko: "교과서(教科書)는 일본어로 きょうかしょ(教科書). 한자가 동일해요.", ja: "教科書は韓国語で교과서(キョグァソ)。漢字が同一です。" },
  { en: "'Grammar' is 문법 (mun-beop) in Korean and 文法 (bunpō) in Japanese — from 文法.", ko: "문법(文法)은 일본어로 ぶんぽう(文法). 같은 한자예요.", ja: "文法は韓국語で문법(ムンボプ)。同じ漢字です。" },
  { en: "'Vocabulary' is 어휘 (eo-hwi) in Korean and 語彙 (goi) in Japanese — from 語彙.", ko: "어휘(語彙)는 일본어로 ごい(語彙). 한자가 동일해요.", ja: "語彙は韓国語で어휘(オフィ)。漢字が一致します。" },
  { en: "'Reading' is 독서 (dok-seo) in Korean and 読書 (dokusho) in Japanese — from 讀書.", ko: "독서(讀書)는 일본어로 どくしょ(読書). 발음까지 비슷해요!", ja: "読書は韓国語で독서(トクソ)。発音も近いです！" },
  { en: "'Writing' is 작문 (jak-mun) in Korean and 作文 (sakubun) in Japanese — from 作文.", ko: "작문(作文)은 일본어로 さくぶん(作文). 같은 한자에서 왔어요.", ja: "作文は韓国語で작문(チャンムン)。同じ漢字由来です。" },
  { en: "'Pronunciation' is 발음 (bal-eum) in Korean and 発音 (hatsuon) in Japanese — from 發音.", ko: "발음(發音)은 일본어로 はつおん(発音). 한자가 같아요.", ja: "発音は韓国語で발음(パルム)。漢字が同じです。" },
  { en: "'Translation' is 번역 (beon-yeok) in Korean and 翻訳 (hon'yaku) in Japanese — from 飜譯.", ko: "번역(飜譯)은 일본어로 ほんやく(翻訳). 같은 한자 기반이에요.", ja: "翻訳は韓国語で번역(ポニョク)。同じ漢字由来です。" },
  { en: "'Language' is 언어 (eon-eo) in Korean and 言語 (gengo) in Japanese — from 言語.", ko: "언어(言語)는 일본어로 げんご(言語). 한자가 동일해요.", ja: "言語は韓国語で언어(オノ)。漢字が同一です。" },
  { en: "'Culture' is 문화 (mun-hwa) in Korean and 文化 (bunka) in Japanese — from 文化.", ko: "문화(文化)는 일본어로 ぶんか(文化). 발음이 비슷해요!", ja: "文化は韓国語で문화(ムナ)。発音が近いです！" },

  // 51-100: Health/medical vocabulary
  { en: "'Hospital' is 병원 (byeong-won) in Korean and 病院 (byōin) in Japanese — from 病院.", ko: "병원(病院)은 일본어로 びょういん(病院). 한자가 같아요!", ja: "病院は韓国語で병원(ピョンウォン)。漢字が一致します！" },
  { en: "'Doctor' is 의사 (ui-sa) in Korean and 医者 (isha) in Japanese — both from the 醫 character for medicine.", ko: "의사(醫師)는 일본어로 いしゃ(医者). 모두 의학 한자에서 왔어요.", ja: "医者は韓国語で의사(ウィサ)。どちらも医学の漢字由来です。" },
  { en: "'Medicine/drug' is 약 (yak) in Korean and 薬 (kusuri) in Japanese, both written with 藥 — the same character.", ko: "약(藥)은 일본어로 くすり(薬). 같은 한자예요.", ja: "薬は韓国語で약(ヤク)。同じ漢字です。" },
  { en: "'Health' is 건강 (geon-gang) in Korean and 健康 (kenkō) in Japanese — from 健康.", ko: "건강(健康)은 일본어로 けんこう(健康). 한자가 같아요!", ja: "健康は韓国語で건강(コンガン)。漢字が一致します！" },
  { en: "'Fever' is 열 (yeol) in Korean and 熱 (netsu) in Japanese — the same character 熱.", ko: "열(熱)은 일본어로 ねつ(熱). 같은 한자 한 글자예요.", ja: "熱は韓国語で열(ヨル)。同じ一文字の漢字です。" },
  { en: "'Surgery' is 수술 (su-sul) in Korean and 手術 (shujutsu) in Japanese — from 手術.", ko: "수술(手術)은 일본어로 しゅじゅつ(手術). 한자가 동일해요.", ja: "手術は韓국語で수술(ススル)。漢字が同一です。" },
  { en: "'Nurse' is 간호사 (gan-ho-sa) in Korean and 看護師 (kangoshi) in Japanese — from 看護師.", ko: "간호사(看護師)는 일본어로 かんごし(看護師). 같은 한자예요.", ja: "看護師は韓国語で간호사(カンホサ)。同じ漢字です。" },
  { en: "'Pharmacy' is 약국 (yak-guk) in Korean and 薬局 (yakkyoku) in Japanese — from 藥局.", ko: "약국(藥局)은 일본어로 やっきょく(薬局). 한자가 같아요!", ja: "薬局は韓国語で약국(ヤックク)。漢字が一致します！" },
  { en: "'Blood type' is 혈액형 (hyeo-raek-hyeong) in Korean and 血液型 (ketsuekigata) in Japanese — both use 血液型.", ko: "혈액형(血液型)은 일본어로 けつえきがた(血液型). 같은 한자예요.", ja: "血液型は韓国語で혈액형(ヒョレクヒョン)。漢字が完全一致です。" },
  { en: "'Dentist' is 치과 (chi-gwa) in Korean and 歯科 (shika) in Japanese — from 齒科.", ko: "치과(齒科)는 일본어로 しか(歯科). 같은 한자 기반이에요.", ja: "歯科は韓국語で치과(チグァ)。同じ漢字由来です。" },
  { en: "'Allergy' is 알레르기 in Korean and アレルギー in Japanese — both borrowed from German 'Allergie'!", ko: "알레르기는 일본어로 アレルギー. 둘 다 독일어에서 빌려온 말이에요!", ja: "アレルギーは韓国語で알레르기。どちらもドイツ語からの借用語です！" },
  { en: "'Vitamin' is 비타민 in Korean and ビタミン in Japanese — both from English 'vitamin'.", ko: "비타민은 일본어로 ビタミン. 같은 영어에서 왔어요.", ja: "ビタミンは韓国語で비타민。同じ英語由来です。" },
  { en: "'Exercise' is 운동 (un-dong) in Korean and 運動 (undō) in Japanese — from 運動.", ko: "운동(運動)은 일본어로 うんどう(運動). 발음도 비슷하고 한자도 같아요!", ja: "運動は韓国語で운동(ウンドン)。発音も漢字も似ています！" },
  { en: "'Sleep' is 수면 (su-myeon) in Korean and 睡眠 (suimin) in Japanese — from 睡眠.", ko: "수면(睡眠)은 일본어로 すいみん(睡眠). 한자가 동일해요.", ja: "睡眠は韓国語で수면(スミョン)。漢字が同一です。" },
  { en: "'Stress' is 스트레스 in Korean and ストレス in Japanese — both from English 'stress'.", ko: "스트레스는 일본어로 ストレス. 둘 다 영어에서 온 말이에요.", ja: "ストレスは韓国語で스트레스。どちらも英語由来です。" },
  { en: "'Ambulance' is 구급차 (gu-geup-cha) in Korean and 救急車 (kyūkyūsha) in Japanese — from 救急車.", ko: "구급차(救急車)는 일본어로 きゅうきゅうしゃ(救急車). 같은 한자예요!", ja: "救急車は韓国語で구급차(クグプチャ)。漢字が一致します！" },
  { en: "'Heartbeat' is 심장 (sim-jang) in Korean and 心臓 (shinzō) in Japanese — from 心臟.", ko: "심장(心臟)은 일본어로 しんぞう(心臓). 같은 한자 기반이에요.", ja: "心臓は韓国語で심장(シムジャン)。同じ漢字由来です。" },
  { en: "'Headache' is 두통 (du-tong) in Korean and 頭痛 (zutsū) in Japanese — from 頭痛.", ko: "두통(頭痛)은 일본어로 ずつう(頭痛). 한자가 같아요.", ja: "頭痛は韓国語で두통(トゥトン)。漢字が同じです。" },
  { en: "'Infection' is 감염 (gam-yeom) in Korean and 感染 (kansen) in Japanese — from 感染.", ko: "감염(感染)은 일본어로 かんせん(感染). 한자가 동일해요.", ja: "感染は韓国語で감염(カミョム)。漢字が同一です。" },
  { en: "'Recovery' is 회복 (hoe-bok) in Korean and 回復 (kaifuku) in Japanese — from 回復.", ko: "회복(回復)은 일본어로 かいふく(回復). 같은 한자예요.", ja: "回復は韓国語で회복(フェボク)。同じ漢字です。" },
  { en: "'Cancer' is 암 (am) in Korean and 癌 (gan) in Japanese — both use the character 癌.", ko: "암(癌)은 일본어로 がん(癌). 같은 한자 한 글자예요.", ja: "癌は韓国語で암(アム)。同じ一文字の漢字です。" },
  { en: "'Diabetes' is 당뇨병 (dang-nyo-byeong) in Korean and 糖尿病 (tōnyōbyō) in Japanese — from 糖尿病.", ko: "당뇨병(糖尿病)은 일본어로 とうにょうびょう(糖尿病). 같은 한자예요.", ja: "糖尿病は韓국語で당뇨병(タンニョビョン)。漢字が一致します。" },
  { en: "'Vaccine' is 백신 in Korean and ワクチン in Japanese — Korean borrowed from English, Japanese from German 'Vakzin'.", ko: "백신은 영어에서, 일본어 ワクチン은 독일어에서 왔어요. 같은 개념이지만 다른 언어 경로!", ja: "韓국語の백신は英語から、ワクチンはドイツ語から。同じ概念でも借用元が違います！" },
  { en: "'Calorie' is 칼로리 in Korean and カロリー in Japanese — both from French 'calorie'.", ko: "칼로리와 カロリー는 둘 다 프랑스어에서 왔어요.", ja: "カロリーと칼로리はどちらもフランス語由来です。" },
  { en: "'Diet' is 다이어트 in Korean and ダイエット in Japanese — both from English 'diet'.", ko: "다이어트와 ダイエット는 같은 영어 단어에서 왔어요.", ja: "ダイエットと다이어트は同じ英語由来です。" },

  // 101-150: Work/society vocabulary
  { en: "'Company/firm' is 회사 (hoe-sa) in Korean and 会社 (kaisha) in Japanese — from 會社.", ko: "회사(會社)는 일본어로 かいしゃ(会社). 한자가 똑같아요!", ja: "会社は韓国語で회사(フェサ)。漢字が完全一致です！" },
  { en: "'Office' is 사무실 (sa-mu-sil) in Korean and 事務室 (jimusshitsu) in Japanese — from 事務室.", ko: "사무실(事務室)은 일본어로 じむしつ(事務室). 같은 한자예요.", ja: "事務室は韓国語で사무실(サムシル)。同じ漢字です。" },
  { en: "'Meeting' is 회의 (hoe-ui) in Korean and 会議 (kaigi) in Japanese — from 會議.", ko: "회의(會議)는 일본어로 かいぎ(会議). 발음도 비슷하고 한자도 같아요!", ja: "会議は韓国語で회의(フェウィ)。発音も漢字も似ています！" },
  { en: "'President/CEO' is 사장 (sa-jang) in Korean and 社長 (shachō) in Japanese — from 社長.", ko: "사장(社長)은 일본어로 しゃちょう(社長). 한자가 동일해요.", ja: "社長は韓국語で사장(サジャン)。漢字が同一です。" },
  { en: "'Employee' is 직원 (ji-gwon) in Korean and 職員 (shokuin) in Japanese — from 職員.", ko: "직원(職員)은 일본어로 しょくいん(職員). 같은 한자예요.", ja: "職員は韓国語で직원(チグォン)。同じ漢字です。" },
  { en: "'Contract' is 계약 (gye-yak) in Korean and 契約 (keiyaku) in Japanese — from 契約.", ko: "계약(契約)은 일본어로 けいやく(契約). 한자가 같아요!", ja: "契約は韓国語で계약(ケヤク)。漢字が一致します！" },
  { en: "'Salary' is 월급 (wol-geup) in Korean (monthly pay) and 月給 (gekkyū) in Japanese — from 月給.", ko: "월급(月給)은 일본어로 げっきゅう(月給). 한자가 동일해요.", ja: "月給は韓国語で월급(ウォルグプ)。漢字が同一です。" },
  { en: "'Business' is 사업 (sa-eop) in Korean and 事業 (jigyō) in Japanese — from 事業.", ko: "사업(事業)은 일본어로 じぎょう(事業). 한자가 같아요.", ja: "事業は韓国語で사업(サオプ)。漢字が同じです。" },
  { en: "'Economy' is 경제 (gyeong-je) in Korean and 経済 (keizai) in Japanese — from 經濟.", ko: "경제(經濟)는 일본어로 けいざい(経済). 발음이 비슷해요!", ja: "経済は韓国語で경제(キョンジェ)。発音が似ています！" },
  { en: "'Government' is 정부 (jeong-bu) in Korean and 政府 (seifu) in Japanese — from 政府.", ko: "정부(政府)는 일본어로 せいふ(政府). 한자가 동일해요.", ja: "政府は韓국語で정부(チョンブ)。漢字が同一です。" },
  { en: "'Society' is 사회 (sa-hoe) in Korean and 社会 (shakai) in Japanese — from 社會.", ko: "사회(社會)는 일본어로 しゃかい(社会). 한자가 같아요.", ja: "社会は韓国語で사회(サフェ)。漢字が一致します。" },
  { en: "'Law' is 법 (beop) in Korean and 法 (hō) in Japanese — same character 法.", ko: "법(法)은 일본어로 ほう(法). 같은 한자 한 글자예요.", ja: "法は韓国語で법(ポプ)。同じ一文字の漢字です。" },
  { en: "'Politics' is 정치 (jeong-chi) in Korean and 政治 (seiji) in Japanese — from 政治.", ko: "정치(政治)는 일본어로 せいじ(政治). 한자가 같아요.", ja: "政治は韓国語で정치(チョンチ)。漢字が同じです。" },
  { en: "'Technology' is 기술 (gi-sul) in Korean and 技術 (gijutsu) in Japanese — from 技術.", ko: "기술(技術)은 일본어로 ぎじゅつ(技術). 발음도 비슷하고 한자도 같아요!", ja: "技術は韓国語で기술(キスル)。発音も漢字も似ています！" },
  { en: "'Environment' is 환경 (hwan-gyeong) in Korean and 環境 (kankyō) in Japanese — from 環境.", ko: "환경(環境)은 일본어로 かんきょう(環境). 한자가 동일해요.", ja: "環境は韓国語で환경(ファンギョン)。漢字が同一です。" },
  { en: "'Industry' is 산업 (san-eop) in Korean and 産業 (sangyō) in Japanese — from 産業.", ko: "산업(産業)은 일본어로 さんぎょう(産業). 발음도 비슷해요!", ja: "産業は韓国語で산업(サノプ)。発音も似ています！" },
  { en: "'Trade/commerce' is 무역 (mu-yeok) in Korean and 貿易 (bōeki) in Japanese — from 貿易.", ko: "무역(貿易)은 일본어로 ぼうえき(貿易). 한자가 같아요.", ja: "貿易は韓국語で무역(ムヨク)。漢字が一致します。" },
  { en: "'Tax' is 세금 (se-geum) in Korean and 税金 (zeikin) in Japanese — from 稅金.", ko: "세금(稅金)은 일본어로 ぜいきん(税金). 한자가 같아요.", ja: "税金は韓国語で세금(セグム)。漢字が同じです。" },
  { en: "'Newspaper' is 신문 (sin-mun) in Korean and 新聞 (shinbun) in Japanese — from 新聞.", ko: "신문(新聞)은 일본어로 しんぶん(新聞). 한자가 동일해요!", ja: "新聞は韓国語で신문(シンムン)。漢字が同一です！" },
  { en: "'Telephone' is 전화 (jeon-hwa) in Korean and 電話 (denwa) in Japanese — from 電話.", ko: "전화(電話)는 일본어로 でんわ(電話). 한자가 같아요.", ja: "電話は韓国語で전화(チョナ)。漢字が同じです。" },
  { en: "'Internet' is 인터넷 in Korean and インターネット in Japanese — both from English 'internet'.", ko: "인터넷과 インターネット는 둘 다 영어에서 왔어요.", ja: "インターネットと인터넷はどちらも英語由来です。" },
  { en: "'Computer' is 컴퓨터 in Korean and コンピューター in Japanese — both from English 'computer'.", ko: "컴퓨터와 コンピューター는 같은 영어 단어에서 왔어요.", ja: "コンピューターと컴퓨터は同じ英語由来です。" },
  { en: "'Energy' is 에너지 in Korean and エネルギー in Japanese — Korean from English, Japanese from German 'Energie'.", ko: "에너지는 영어, エネルギー는 독일어에서 왔어요. 같은 개념, 다른 경로!", ja: "에너지は英語から、エネルギーはドイツ語から。同じ意味でも借用元が違います！" },
  { en: "'Police' is 경찰 (gyeong-chal) in Korean and 警察 (keisatsu) in Japanese — from 警察.", ko: "경찰(警察)은 일본어로 けいさつ(警察). 한자가 동일해요.", ja: "警察は韓国語で경찰(キョンチャル)。漢字が同一です。" },
  { en: "'International' is 국제 (guk-je) in Korean and 国際 (kokusai) in Japanese — from 國際.", ko: "국제(國際)는 일본어로 こくさい(国際). 한자가 같아요.", ja: "国際は韓국語で국제(ククチェ)。漢字が一致します。" },

  // 151-200: Loanwords from the same foreign sources
  { en: "Both Korean 커피 (keopi) and Japanese コーヒー (kōhī) come from Dutch 'koffie' — coffee reached East Asia via Dutch traders!", ko: "커피와 コーヒー는 둘 다 네덜란드어 koffie에서 왔어요. 커피가 동아시아에 네덜란드 무역상을 통해 전해졌거든요!", ja: "커피とコーヒーはどちらもオランダ語のkoffieが起源。コーヒーはオランダ商人を通じて東アジアに伝わりました！" },
  { en: "Both Korean 빵 (ppang) and Japanese パン (pan) come from Portuguese 'pão' (bread) — brought by 16th-century missionaries.", ko: "빵과 パン은 둘 다 포르투갈어 pão에서 왔어요. 16세기 선교사들이 가져온 단어예요!", ja: "빵とパンはどちらもポルトガル語のpão（パン）が起源。16世紀の宣教師が伝えました！" },
  { en: "Both Korean 담배 (dam-bae) and Japanese タバコ (tabako) trace to Portuguese 'tabaco' — tobacco also arrived via early explorers.", ko: "담배와 タバコ는 모두 포르투갈어 tabaco에서 왔어요.", ja: "담배とタバコはどちらもポルトガル語のtabaco由来です。" },
  { en: "Both Korean 고무 (go-mu) and Japanese ゴム (gomu) come from Dutch 'gom' (rubber/gum).", ko: "고무와 ゴム는 둘 다 네덜란드어 gom에서 왔어요.", ja: "고무とゴムはどちらもオランダ語のgom由来です。" },
  { en: "Both Korean 피아노 and Japanese ピアノ come from Italian 'pianoforte' — both borrowed the same shortened form.", ko: "피아노와 ピアノ는 둘 다 이탈리아어에서 왔어요.", ja: "ピアノと피아노はどちらもイタリア語由来です。" },
  { en: "Both Korean 기타 (gi-ta) and Japanese ギター (gitā) come from Spanish 'guitarra'.", ko: "기타와 ギター는 둘 다 스페인어 guitarra에서 왔어요.", ja: "ギターと기타はどちらもスペイン語のguitarra由来です。" },
  { en: "Both Korean 아이스크림 and Japanese アイスクリーム come from English 'ice cream'.", ko: "아이스크림과 アイスクリーム은 같은 영어에서 왔어요.", ja: "アイスクリームと아이스크림は同じ英語由来です。" },
  { en: "Both Korean 초콜릿 and Japanese チョコレート come from Spanish 'chocolate', originally from Nahuatl 'xocolātl'.", ko: "초콜릿과 チョコレート는 스페인어를 통해 나후아틀어에서 온 단어예요!", ja: "チョコレートと초콜릿はスペイン語経由でナワトル語由来です！" },
  { en: "Both Korean 바나나 and Japanese バナナ come from the word 'banana', originally from West African languages.", ko: "바나나와 バナナ는 서아프리카 언어에서 온 단어예요.", ja: "バナナと바나나は西アフリカ語由来の言葉です。" },
  { en: "Both Korean 드라마 and Japanese ドラマ come from Greek 'drama' via English.", ko: "드라마와 ドラマ는 영어를 통해 그리스어 drama에서 왔어요.", ja: "ドラマと드라마はギリシャ語のdrama由来です。" },
  { en: "Both Korean 카메라 and Japanese カメラ come from Dutch 'camera obscura'.", ko: "카메라와 カメラ는 네덜란드어 camera obscura에서 왔어요.", ja: "カメラと카메라はオランダ語のcamera obscura由来です。" },
  { en: "Both Korean 아파트 and Japanese アパート come from English 'apartment'.", ko: "아파트와 アパート는 같은 영어 apartment에서 왔어요.", ja: "アパートと아파트は英語のapartment由来です。" },
  { en: "Both Korean 버스 and Japanese バス come from English 'bus'.", ko: "버스와 バス는 같은 영어 bus에서 왔어요.", ja: "バスと버스は同じ英語のbus由来です。" },
  { en: "Both Korean 택시 and Japanese タクシー come from English 'taxi'.", ko: "택시와 タクシー는 같은 영어 taxi에서 왔어요.", ja: "タクシーと택시は同じ英語のtaxi由来です。" },
  { en: "Both Korean 호텔 and Japanese ホテル come from French 'hôtel'.", ko: "호텔과 ホテル는 프랑스어 hôtel에서 왔어요.", ja: "ホテルと호텔はフランス語のhôtel由来です。" },
  { en: "Both Korean 레스토랑 and Japanese レストラン come from French 'restaurant'.", ko: "레스토랑과 レストラン는 프랑스어 restaurant에서 왔어요.", ja: "レストランと레스토랑はフランス語のrestaurant由来です。" },
  { en: "Both Korean 샴페인 and Japanese シャンパン come from French 'champagne'.", ko: "샴페인과 シャンパン은 프랑스어 champagne에서 왔어요.", ja: "シャンパンと샴페인はフランス語のchampagne由来です。" },
  { en: "Both Korean 바이올린 and Japanese バイオリン come from Italian 'violino'.", ko: "바이올린과 バイオリン은 이탈리아어 violino에서 왔어요.", ja: "バイオリンと바이올린はイタリア語のviolino由来です。" },
  { en: "Both Korean 오페라 and Japanese オペラ come from Italian 'opera'.", ko: "오페라와 オペラ는 이탈리아어에서 왔어요.", ja: "オペラと오페라はイタリア語由来です。" },
  { en: "Both Korean 럭비 and Japanese ラグビー come from English 'rugby', named after Rugby School in England.", ko: "럭비와 ラグビー는 영국 럭비 학교 이름에서 온 단어예요!", ja: "ラグビーと럭비は英国のラグビー校から来た言葉です！" },
  { en: "Both Korean 골프 and Japanese ゴルフ come from English 'golf', possibly from Dutch 'kolf'.", ko: "골프와 ゴルフ는 영어 golf에서, 그 영어는 네덜란드어 kolf에서 왔을 수 있어요.", ja: "ゴルフと골프は英語のgolf由来、その英語はオランダ語のkolfから来た可能性があります。" },
  { en: "Both Korean 테니스 and Japanese テニス come from English 'tennis'.", ko: "테니스와 テニス는 같은 영어 tennis에서 왔어요.", ja: "テニスと테니스は同じ英語のtennis由来です。" },
  { en: "Both Korean 마라톤 and Japanese マラソン come from Greek 'Marathon' — the ancient battle site.", ko: "마라톤과 マラソン은 그리스 지명 Marathon에서 왔어요.", ja: "マラソンと마라톤はギリシャの地名Marathon由来です。" },
  { en: "Both Korean 올림픽 and Japanese オリンピック come from Greek 'Olympikos'.", ko: "올림픽과 オリンピック는 그리스어 Olympikos에서 왔어요.", ja: "オリンピックと올림픽はギリシャ語のOlympikos由来です。" },
  { en: "Both Korean 피자 and Japanese ピザ come from Italian 'pizza'.", ko: "피자와 ピザ는 이탈리아어 pizza에서 왔어요.", ja: "ピザと피자はイタリア語のpizza由来です。" },

  // 201-250: Grammar parallels
  { en: "Both Korean and Japanese are SOV (Subject-Object-Verb) languages. English is SVO. So 'I apple eat' is the natural order in both!", ko: "한국어와 일본어는 둘 다 SOV 언어예요. '나는 사과를 먹는다'처럼 동사가 마지막에 와요!", ja: "韓国語も日本語もSOV言語です。「私はりんごを食べる」のように動詞が最後に来ます！" },
  { en: "Both Korean 는/은 and Japanese は (wa) work as topic markers — they highlight what the sentence is ABOUT, not necessarily the subject.", ko: "한국어 는/은과 일본어 は는 둘 다 화제 표지예요. 문장의 주어가 아니라 '화제'를 나타내요!", ja: "韓国語の는/은と日本語のははどちらも話題マーカー。文の主語ではなく「話題」を示します！" },
  { en: "Both Korean 가/이 and Japanese が (ga) are subject markers. Korean and Japanese both distinguish topic (는/は) from subject (가/が)!", ko: "한국어 가/이와 일본어 が는 둘 다 주격 표지예요. 두 언어 모두 화제와 주어를 구별해요!", ja: "韓국語の가/이と日本語のがはどちらも主格マーカー。両言語とも話題と主語を区別します！" },
  { en: "Both Korean 을/를 and Japanese を (wo/o) mark the direct object. They work exactly the same way!", ko: "한국어 을/를과 일본어 を는 둘 다 목적격 표지예요. 완전히 같은 방식으로 작동해요!", ja: "韓国語の을/를と日本語のをはどちらも目的格マーカー。まったく同じ働きをします！" },
  { en: "Both Korean 에 and Japanese に (ni) can mark location ('at/in') and direction ('to/toward') — the same particle does double duty.", ko: "한국어 에와 일본어 に는 둘 다 위치('~에서')와 방향('~으로')을 나타낼 수 있어요.", ja: "韓国語の에と日本語のにはどちらも場所（「で」「に」）と方向を表せます。" },
  { en: "Both Korean 에서 and Japanese で (de) can mark the location where an action takes place: '학교에서/学校で 공부해요/勉強します'.", ko: "한국어 에서와 일본어 で는 둘 다 동작이 일어나는 장소를 표시해요.", ja: "韓国語の에서と日本語のでは、どちらも動作が起こる場所を示します。" },
  { en: "Both Korean 의 and Japanese の (no) are possessive markers: '나의 책/私の本' = 'my book'. They work identically!", ko: "한국어 의와 일본어 の는 둘 다 소유격 표지예요. '나의 책/私の本'처럼 완전히 같아요!", ja: "韓국語の의と日本語ののは、どちらも所有格マーカー。「나의 책/私の本」のように同じ使い方です！" },
  { en: "Both languages put adjectives BEFORE nouns: 'big house' is 큰 집 (Korean) and 大きい家 (Japanese) — adjective first, then noun.", ko: "두 언어 모두 형용사가 명사 앞에 와요. '큰 집'과 '大きい家'처럼요!", ja: "両言語とも形容詞は名詞の前に来ます。「큰 집」と「大きい家」のように！" },
  { en: "Verb tenses in both languages are expressed by endings attached to the verb stem — not by separate auxiliary words as in English.", ko: "두 언어 모두 동사 어간에 어미를 붙여 시제를 나타내요. 영어처럼 별도의 조동사를 쓰지 않아요.", ja: "両言語とも動詞の語幹に語尾をつけて時制を表します。英語のような別の助動詞は使いません。" },
  { en: "Both languages have honorific/polite speech levels — you speak differently to elders, strangers, or subordinates. English has no equivalent!", ko: "두 언어 모두 경어/존댓말이 있어요. 어른, 낯선 사람, 아랫사람에게 다르게 말해요. 영어에는 없는 개념이에요!", ja: "両言語とも敬語があります。目上の人、知らない人、部下には話し方が変わります。英語にはない概念です！" },
  { en: "Questions in both Korean and Japanese are formed just by changing the verb ending — not by inverting subject and verb as in English.", ko: "두 언어 모두 동사 어미만 바꿔서 의문문을 만들어요. 영어처럼 주어와 동사를 뒤집지 않아요.", ja: "両言語とも動詞の語尾を変えるだけで疑問文になります。英語のように語順を変えません。" },
  { en: "Both Korean -고 and Japanese て (te) are used to connect two verb clauses: 'eat and go' = 먹고 가다 / 食べて行く.", ko: "한국어 -고와 일본어 て는 둘 다 동사절을 연결해요. '먹고 가다'와 '食べて行く'처럼요.", ja: "韓国語の-고と日本語のてはどちらも動詞節を接続します。「먹고 가다」と「食べて行く」のように。" },
  { en: "Both languages have counter words: Korean 개, 명, 권 and Japanese 個, 人, 冊 are used when counting objects, people, and books.", ko: "두 언어 모두 조수사가 있어요. 사과 한 개, 사람 한 명처럼 명사마다 다른 단위를 써요.", ja: "両言語とも助数詞があります。りんご一個、人一人のように、名詞ごとに異なる単位を使います。" },
  { en: "The negative form in both languages is made by adding a negative ending to the verb: 먹지 않다 (Korean) and 食べない (Japanese).", ko: "두 언어 모두 동사에 부정 어미를 붙여 부정형을 만들어요.", ja: "両言語とも動詞に否定語尾をつけて否定形を作ります。" },
  { en: "Both Korean and Japanese use postpositions (after the noun), unlike European languages which use prepositions (before the noun).", ko: "두 언어 모두 후치사(명사 뒤에 오는 조사)를 써요. 유럽어처럼 전치사(명사 앞)가 아니에요.", ja: "両言語とも後置詞（名詞の後）を使います。欧州語のような前置詞（名詞の前）ではありません。" },
  { en: "In both Korean and Japanese, the subject can be dropped when it's understood from context — 'going to school' can be said without 'I'.", ko: "두 언어 모두 문맥상 명확할 때 주어를 생략할 수 있어요. '학교 가요'처럼 '나'를 안 써도 돼요.", ja: "両言語とも、文脈から明らかな場合は主語を省略できます。「学校行きます」のように「私は」なしでOK。" },
  { en: "Both languages extensively use 'sentence-final particles' that add nuance — Korean -요/-야 and Japanese ね/よ/ね modulate politeness and certainty.", ko: "두 언어 모두 문장 끝에 붙는 조사로 뉘앙스를 더해요. 한국어 -요/-야, 일본어 ね/よ처럼요.", ja: "両言語とも文末助詞でニュアンスを加えます。韓国語の-요/-야、日本語のね/よのように。" },
  { en: "Both Korean and Japanese can express 'want to do' by modifying the verb stem: 먹고 싶다 (Korean) / 食べたい (Japanese).", ko: "두 언어 모두 동사 어간을 변형해서 '~하고 싶다'를 표현해요.", ja: "両言語とも動詞の語幹を変形して「〜したい」を表します。" },
  { en: "The 'even if/although' construction works similarly: 먹어도 (Korean) and 食べても (Japanese) both mean 'even if (I) eat'.", ko: "'-아/어도'(한국어)와 '-ても'(일본어)는 둘 다 '~해도'를 뜻해요.", ja: "「-아/어도」（韓国語）と「-ても」（日本語）はどちらも「〜しても」を意味します。" },
  { en: "Both Korean and Japanese use conjunctive endings to make relative clauses — the clause modifies a noun by coming before it.", ko: "두 언어 모두 관형사형 어미로 관계절을 만들어요. 절이 명사 앞에서 수식해요.", ja: "両言語とも連体形で関係節を作ります。節は名詞の前に来て修飾します。" },
  { en: "Conditional 'if' uses verb-ending constructions: 먹으면 (Korean) and 食べれば (Japanese) both mean 'if (I) eat'.", ko: "조건절 '~면'(한국어)과 '~ば/たら'(일본어)는 같은 방식으로 작동해요.", ja: "条件節の「〜면」（韓国語）と「〜ば/たら」（日本語）は同じように機能します。" },
  { en: "Both languages stack verb endings to make complex expressions: 먹어보고 싶었는데요 / 食べてみたかったんですけど — same layering technique!", ko: "두 언어 모두 어미를 겹쳐 복잡한 표현을 만들어요. 구조가 완전히 같아요!", ja: "両言語とも語尾を重ねて複雑な表現を作ります。構造がまったく同じです！" },
  { en: "The 'let's do X' construction: 먹자 (Korean) and 食べよう (Japanese) are both volitional verb forms.", ko: "청유형 '먹자'(한국어)와 '食べよう'(일본어)는 둘 다 의지/권유를 표현해요.", ja: "勧誘形の「먹자」（韓国語）と「食べよう」（日本語）はどちらも意志・勧誘を表します。" },
  { en: "Both languages have 'polite request' forms: 주세요 (ju-se-yo) in Korean and ください (kudasai) in Japanese both mean 'please give me' or 'please do'.", ko: "'주세요'(한국어)와 'ください'(일본어)는 둘 다 정중한 요청을 나타내요.", ja: "「주세요」（韓国語）と「ください」（日本語）はどちらも丁寧な依頼を表します。" },
  { en: "Neither Korean nor Japanese have articles like English 'a/an/the'. Context determines definiteness!", ko: "한국어와 일본어에는 영어의 a/an/the 같은 관사가 없어요. 문맥으로 파악해요!", ja: "韓国語も日本語も、英語のa/an/theのような冠詞がありません。文脈で判断します！" },

  // 251-300: Days, time expressions
  { en: "The days of the week in Korean and Japanese use the same Chinese characters: 月火水木金土日 (Moon, Fire, Water, Wood, Gold, Earth, Sun).", ko: "한국어와 일본어 요일은 같은 한자를 써요: 월화수목금토일 = 달 불 물 나무 금 흙 해!", ja: "韓国語と日本語の曜日は同じ漢字を使います：月火水木金土日（月・火・水・木・金・土・日）！" },
  { en: "Monday: 월요일 (wol-yo-il) in Korean and 月曜日 (getsuyōbi) in Japanese — both literally mean 'Moon Day'.", ko: "월요일(月曜日)과 月曜日(げつようび)는 둘 다 '달의 날'이라는 뜻이에요!", ja: "월요일（ウォリョイル）と月曜日（げつようび）はどちらも「月の日」という意味です！" },
  { en: "Tuesday: 화요일 (hwa-yo-il) in Korean and 火曜日 (kayōbi) in Japanese — both literally mean 'Fire Day'.", ko: "화요일(火曜日)과 火曜日(かようび)는 둘 다 '불의 날'이에요!", ja: "화요일（ファヨイル）と火曜日（かようび）はどちらも「火の日」です！" },
  { en: "Wednesday: 수요일 (su-yo-il) in Korean and 水曜日 (suiyōbi) in Japanese — both mean 'Water Day'.", ko: "수요일(水曜日)과 水曜日(すいようび)는 '물의 날'이에요!", ja: "수요일（スヨイル）と水曜日（すいようび）は「水の日」です！" },
  { en: "Thursday: 목요일 (mok-yo-il) in Korean and 木曜日 (mokuyōbi) in Japanese — both mean 'Wood/Tree Day'.", ko: "목요일(木曜日)과 木曜日(もくようび)는 '나무의 날'이에요!", ja: "목요일（モギョイル）と木曜日（もくようび）は「木の日」です！" },
  { en: "Friday: 금요일 (geum-yo-il) in Korean and 金曜日 (kin'yōbi) in Japanese — both mean 'Gold/Metal Day'.", ko: "금요일(金曜日)과 金曜日(きんようび)는 '금(쇠)의 날'이에요!", ja: "금요일（クミョイル）と金曜日（きんようび）は「金の日」です！" },
  { en: "Saturday: 토요일 (to-yo-il) in Korean and 土曜日 (doyōbi) in Japanese — both mean 'Earth/Soil Day'.", ko: "토요일(土曜日)과 土曜日(どようび)는 '흙(땅)의 날'이에요!", ja: "토요일（トヨイル）と土曜日（どようび）は「土の日」です！" },
  { en: "Sunday: 일요일 (il-yo-il) in Korean and 日曜日 (nichiyōbi) in Japanese — both mean 'Sun Day', just like English 'Sunday'!", ko: "일요일(日曜日)과 日曜日(にちようび)는 '해의 날'이에요. 영어 Sunday와 똑같은 뜻!", ja: "일요일（イリョイル）と日曜日（にちようび）は「太陽の日」。英語のSundayと同じ意味です！" },
  { en: "The 12 zodiac signs are used in both Korea and Japan for years: 쥐 띠/子年 (rat), 소 띠/丑年 (ox), 범 띠/寅年 (tiger)...", ko: "한국과 일본 모두 12지(띠)를 써요: 쥐, 소, 호랑이, 토끼, 용, 뱀, 말, 양, 원숭이, 닭, 개, 돼지!", ja: "韓国と日本どちらも十二支を使います：鼠・牛・虎・兎・龍・蛇・馬・羊・猿・鶏・犬・猪！" },
  { en: "'Year' is 년/년도 in Korean and 年 (nen) in Japanese — both from the same character 年. '2024年' is read similarly in both.", ko: "연도(年度)는 일본어로 ねんど(年度). 한자가 같고 쓰임도 비슷해요.", ja: "年度（ねんど）は韓国語で연도（ヨンド）。漢字が同じで使い方も似ています。" },
  { en: "'Month' uses the same Chinese characters: 1월 = 一月 (ichigatsu/January). The system is identical!", ko: "월(月)은 일본어로 月(がつ/つき). 1월=1月(いちがつ)처럼 숫자+月 구조가 같아요!", ja: "月（がつ）は韓국語で월（ウォル）。1월=1月のように数字＋月の構造が同じです！" },
  { en: "'Today' is 오늘 (o-neul) in Korean and 今日 (kyō/konnichi) in Japanese — these are different words, but both derived from native roots meaning 'this day'.", ko: "오늘은 순우리말, 今日(きょう)는 순일본어예요. 둘 다 '이 날'이라는 뜻의 고유어예요.", ja: "오늘は固有韓国語、今日（きょう）は固有日本語。どちらも「この日」という意味の和語・固有語です。" },
  { en: "'Yesterday' is 어제 (eo-je) in Korean and 昨日 (kinō) in Japanese — different native words. But the Sino-Korean 작일 (昨日) matches!", ko: "어제는 순우리말, 昨日(きのう)는 순일본어예요. 하지만 한자어로는 둘 다 昨日(작일)!", ja: "어제は固有韓国語、昨日（きのう）は固有日本語。でも漢字では어제＝昨日（作一）で一致！" },
  { en: "'Morning' is 아침 in Korean (native word) and 朝 (asa) in Japanese — different words, but the Sino-Korean 조반 (朝飯) = Japanese 朝飯 (asahan).", ko: "아침은 순우리말, 朝(あさ)는 순일본어예요. 하지만 아침밥=朝飯처럼 한자 표현은 같아요!", ja: "아침は固有韓国語、朝（あさ）は固有日本語。でも「朝飯」のような漢字表現では一致します！" },
  { en: "'Now' is 지금 (ji-geum) in Korean and 今 (ima) in Japanese — the Sino-Korean 지금(只今) matches Japanese ただいま(只今), which means 'I'm home'!", ko: "지금(只今)은 순우리말이지만, 일본어 ただいま(只今)와 한자가 같아요. 뜻은 다르지만 재미있죠!", ja: "지금（只今）は固有韓국語的に使われますが、日本語のただいま（只今）と漢字が同じ！意味は違いますが面白いですね！" },
  { en: "The 24-hour system is commonly used in both Korea and Japan for official times — train schedules, TV guides, etc.", ko: "한국과 일본 모두 공식적인 시간 표기에 24시간제를 많이 써요. 기차 시간표나 TV 안내 등에서요.", ja: "韓国も日本も、公式な時間表記には24時間制がよく使われます。電車の時刻表やTV番組表など。" },
  { en: "'Midnight' is 자정 (ja-jeong) in Korean and 真夜中 (mayonaka) in Japanese — but the Sino-Korean 子正(자정) and Japanese 子の刻 both reference the 'Rat hour' in the old system.", ko: "자정은 예로부터 '자시(子時)', 즉 쥐의 시간이었어요. 일본도 마찬가지예요!", ja: "자정（자정）は昔の「子の刻」から来ています。日本も同じ時刻の表し方でした！" },
  { en: "Both Korea and Japan traditionally used the lunar calendar — many festivals like Chuseok/Otsukimi fall on lunar dates.", ko: "한국과 일본 모두 전통적으로 음력을 사용했어요. 추석이나 お月見 같은 명절이 음력 날짜에 있어요.", ja: "韓国も日本も伝統的に旧暦を使っていました。秋夕やお月見など、祭りが旧暦の日付にあります。" },
  { en: "New Year in both countries features special foods: 떡국 (rice cake soup) in Korea and お雑煮 (ozōni) in Japan — both are New Year soups with rice cakes!", ko: "한국의 떡국과 일본의 お雑煮는 둘 다 새해에 먹는 떡 국물 요리예요! 우연이 아닐지도 몰라요!", ja: "韓国の떡국と日本のお雑煮は、どちらも正月に食べるお餅の入ったスープ料理です！偶然ではないかもしれません！" },
  { en: "Both Korean and Japanese number systems have two types: native numbers (하나/ひとつ) and Sino-Korean/Japanese numbers (일/いち). Both use the same Chinese-origin numerals for most formal counting!", ko: "두 언어 모두 고유어 수사(하나/ひとつ)와 한자어 수사(일/いち)가 있어요! 두 체계를 상황에 따라 써요.", ja: "両言語とも固有語数詞（하나/ひとつ）と漢字語数詞（일/いち）があります！場面によって使い分けます。" },
  { en: "Counting age: Koreans traditionally count age differently — born as '1' and gaining a year each New Year. Japan follows the Western system now, but the traditional 数え年 (kazoe-doshi) was similar!", ko: "한국의 전통 나이 계산법(태어나면 1살)과 일본의 数え年는 비슷한 방식이었어요!", ja: "韓国の伝統的な年齢の数え方（生まれたら1歳）と日本の数え年は似た方式でした！" },
  { en: "'Noon' is 정오 (jeong-o) in Korean and 正午 (shōgo) in Japanese — from 正午.", ko: "정오(正午)는 일본어로 しょうご(正午). 한자가 같아요.", ja: "正午は韓国語で정오（チョンオ）。漢字が同じです。" },
  { en: "'Schedule' is 일정 (il-jeong) in Korean and 日程 (nittei) in Japanese — from 日程.", ko: "일정(日程)은 일본어로 にってい(日程). 한자가 동일해요.", ja: "日程は韓国語で일정（イルチョン）。漢字が同一です。" },
  { en: "'Anniversary' is 기념일 (gi-nyeom-il) in Korean and 記念日 (kinenbi) in Japanese — from 記念日.", ko: "기념일(記念日)은 일본어로 きねんび(記念日). 한자가 같아요!", ja: "記念日は韓国語で기념일（キニョミル）。漢字が一致します！" },

  // 301-350: Cultural connections
  { en: "Both Korea and Japan have strong Confucian traditions of respecting elders — formal speech levels in both languages reflect this value.", ko: "한국과 일본 모두 유교적 전통에서 어른을 공경해요. 두 언어의 경어 체계가 이를 반영해요.", ja: "韓国も日本も儒教的な伝統から目上の人を敬います。両言語の敬語体系はこの価値観を反映しています。" },
  { en: "'Thank you' in both languages has formal and informal levels: 감사합니다/고마워요 in Korean and ありがとうございます/ありがとう in Japanese.", ko: "'감사합니다'는 공식적, '고마워'는 친근한 표현. 일본어도 ありがとうございます/ありがとう로 같은 구조예요.", ja: "「감사합니다」は丁寧、「고마워」は親しみやすい表現。日本語も「ありがとうございます/ありがとう」と同じ構造です。" },
  { en: "Bowing as a greeting is common in both Korean and Japanese cultures — though the angle and meaning can differ slightly.", ko: "인사할 때 허리를 숙이는 것은 한국과 일본의 공통 문화예요. 각도와 의미는 조금 달라요.", ja: "お辞儀で挨拶するのは韓国と日本の共通文化です。ただし角度や意味は少し異なります。" },
  { en: "Both Korean 된장찌개 (doenjang-jjigae) and Japanese 味噌汁 (miso soup) are fermented soybean-based dishes central to daily meals.", ko: "된장찌개와 味噌汁는 둘 다 발효 콩으로 만든 음식으로, 두 나라 일상 식사의 핵심이에요!", ja: "된장찌개と味噌汁はどちらも発酵大豆を使った料理で、両国の日常食の中心です！" },
  { en: "Both Korean 김치 and Japanese 漬物 (tsukemono) are fermented/pickled vegetable side dishes served with every meal.", ko: "김치와 漬物(つけもの)는 둘 다 발효/절인 야채 반찬으로 매 끼니에 나와요.", ja: "김치と漬物（つけもの）はどちらも発酵・漬けた野菜の副菜で、毎食出てきます。" },
  { en: "Rice is the staple of both Korean and Japanese cuisine — 밥 (bap) in Korean and ご飯 (gohan) in Japanese both mean both 'rice' and 'meal'!", ko: "밥은 '쌀밥'이기도 하고 '식사'이기도 해요. 일본어 ご飯(ごはん)도 같은 이중 뜻이에요!", ja: "「ご飯」は「米飯」でもあり「食事」でもあります。韓国語の밥も同じ二重の意味を持ちます！" },
  { en: "Both Korea and Japan have a tradition of communal hot-pot dining: 전골/샤부샤부 in Korea and 鍋料理/すき焼き in Japan.", ko: "한국의 전골/샤부샤부와 일본의 鍋料理는 모두 함께 먹는 냄비 요리 전통이에요!", ja: "韓国の전골/샤부샤부と日本の鍋料理は、どちらも鍋を囲む共食の伝統です！" },
  { en: "Both cultures have a tradition of giving and receiving gifts with both hands as a sign of respect.", ko: "두 나라 모두 두 손으로 물건을 주고받는 예의 문화가 있어요.", ja: "両国とも、物を両手で渡したり受け取ったりする礼儀の文化があります。" },
  { en: "Removing shoes before entering a home is a strong custom in both Korea and Japan.", ko: "집에 들어갈 때 신발을 벗는 문화는 한국과 일본 모두 강하게 남아있어요.", ja: "家に入る前に靴を脱ぐ文化は韓国と日本どちらにも強く残っています。" },
  { en: "Both Korean 온돌 (ondol, heated floor) and Japanese 炬燵 (kotatsu, heated table) are unique floor-heating traditions — warmth from below!", ko: "한국의 온돌과 일본의 炬燵(こたつ)는 모두 바닥에서 따뜻함을 전하는 독특한 난방 문화예요!", ja: "韓国のオンドル（床暖房）と日本のこたつ（足元暖房）は、どちらも床から温まる独自の暖房文化です！" },
  { en: "Both countries have strong bathhouse traditions: 찜질방 (jjimjilbang) in Korea and 銭湯 (sentō) / 温泉 (onsen) in Japan.", ko: "한국의 찜질방과 일본의 銭湯/温泉는 둘 다 목욕/사우나 문화의 중심이에요!", ja: "韓国のチムジルバンと日本の銭湯・温泉は、どちらも入浴・サウナ文化の中心です！" },
  { en: "Lunar New Year (설날/お正月) is celebrated in both countries, though with different customs. Japanese New Year moved to January 1 while Korea kept the lunar date.", ko: "설날과 お正月 모두 새해를 기념하지만, 일본은 양력 1월 1일, 한국은 음력 1월 1일로 달라요.", ja: "설날とお正月はどちらも新年を祝いますが、日本は1月1日（新暦）、韓国は旧暦の1月1日と異なります。" },
  { en: "Both Korean 추석 (Chuseok) and Japanese お盆 (Obon) are autumn festivals honoring ancestors — families travel home and pay respects at graves.", ko: "추석과 お盆(おぼん)은 둘 다 조상을 기리는 가을 명절이에요. 가족이 모이고 성묘를 해요.", ja: "秋夕とお盆はどちらも先祖を敬う秋の祭りです。家族が集まり、墓参りをします。" },
  { en: "Both countries share a love of 노래방 (noraebang) and カラオケ (karaoke) — in fact, karaoke was invented in Japan and adopted enthusiastically in Korea!", ko: "노래방 문화는 일본에서 발명된 カラオケ에서 왔어요! 한국이 이를 열정적으로 받아들였죠.", ja: "カラオケは日本で発明され、韓国がノレバンとして熱心に取り入れました！" },
  { en: "Both Korean 태권도 and Japanese 空手 (karate) are East Asian martial arts that emphasize striking techniques.", ko: "태권도와 空手(からて)는 둘 다 동아시아의 타격 중심 무술이에요.", ja: "テコンドーと空手はどちらも東アジアの打撃系武術です。" },
  { en: "Both countries have a strong webtoon/manga culture: 웹툰 (webtoon) in Korea and 漫画 (manga) in Japan are globally influential.", ko: "한국 웹툰과 일본 漫画(まんが)는 둘 다 전 세계에 영향을 끼치는 문화 콘텐츠예요!", ja: "韓国のウェブトゥーンと日本の漫画は、どちらも世界に影響を与える文化コンテンツです！" },
  { en: "Both Korean K-dramas and Japanese anime/dramas have found huge global audiences — East Asian pop culture is a shared phenomenon.", ko: "한국 드라마와 일본 애니메이션/드라마는 둘 다 전 세계 팬을 보유한 콘텐츠예요!", ja: "韓国ドラマと日本のアニメ・ドラマは、どちらも世界中にファンを持つコンテンツです！" },
  { en: "Both Korean and Japanese cuisines make use of seaweed: 김 (gim) in Korea and 海苔 (nori) in Japan — the same product, just different names!", ko: "한국의 김과 일본의 海苔(のり)는 같은 식품이에요. 이름만 달라요!", ja: "韓国の김（キム）と日本の海苔（のり）は同じ食品です。名前が違うだけ！" },
  { en: "Both countries have centuries-old ceramic traditions: Korean 청자 (celadon) and Japanese 有田焼 (Arita-yaki) — both influenced by Chinese pottery.", ko: "한국 청자와 일본 有田焼(ありたやき)는 모두 중국 도예의 영향을 받은 오랜 전통이 있어요.", ja: "韓국の青磁と日本の有田焼は、どちらも中国陶芸の影響を受けた長い伝統があります。" },
  { en: "Traditional music in both countries shares roots: Korean 판소리 and Japanese 能 (Noh) are ancient performing arts with unique vocal techniques.", ko: "한국의 판소리와 일본의 能(のう)는 둘 다 독특한 발성법을 가진 고대 공연 예술이에요.", ja: "韓国のパンソリと日本の能はどちらも独特の発声法を持つ古代の舞台芸術です。" },
  { en: "Both Korean 한복 and Japanese 着物 (kimono) are traditional garments still worn at important ceremonies and celebrations.", ko: "한복과 着物(きもの)는 둘 다 중요한 의례나 명절에 입는 전통 의상이에요.", ja: "韓服（ハンボク）と着物はどちらも大切な式典や祝い事に着る伝統衣装です。" },
  { en: "Both Korea and Japan have Confucian-inspired ancestor veneration rituals: 제사 (jesa) in Korea and 仏壇 (butsudan, ancestral altar) observances in Japan.", ko: "한국의 제사와 일본의 仏壇(ぶつだん) 참배는 둘 다 유교/불교 영향을 받은 조상 추모 의식이에요.", ja: "韓国のチェサと日本の仏壇参りはどちらも儒教・仏教の影響を受けた先祖供養の儀式です。" },
  { en: "The concept of 'nunchi' (눈치) in Korean and 'kuuki wo yomu' (空気を読む) in Japanese — both describe the cultural skill of reading the room.", ko: "눈치(한국)와 空気を読む(일본)는 둘 다 상황을 파악하는 사회적 능력을 가리키는 독특한 개념이에요!", ja: "눈치（韓国）と「空気を読む」（日本）は、どちらも場の空気を読む社会的能力を指す独特の概念です！" },

  // 351-400: Pronunciation/phonology facts
  { en: "Korean has 10 vowels and 14 basic consonants. Japanese has 5 vowels (a, i, u, e, o) and 14 consonants. Both smaller than English's 26 letters!", ko: "한국어는 모음 10개, 자음 14개. 일본어는 모음 5개, 자음 14개. 영어 26글자보다 적어요!", ja: "韓国語は母音10個・子音14個。日本語は母音5個・子音14個。英語の26文字より少ないです！" },
  { en: "Japanese pronunciation is often easier for Korean speakers because Japanese lacks consonant clusters — no 닭 (dak) type endings.", ko: "일본어 발음이 한국인에게 쉬운 이유 중 하나: 일본어는 자음 연속이 없어요. 받침이 없거든요!", ja: "日本語が韓国人に発音しやすい理由のひとつ：日本語には子音の連続がなく、終声がありません！" },
  { en: "Korean 's' (ㅅ) sounds like 's' before most vowels but like 'sh' before 'i' and 'y' — similar to how Japanese し (shi) is different from 'si'.", ko: "한국어 ㅅ은 대부분 's'지만 이/야/여/요/유 앞에서는 'sh' 소리가 나요. 일본어 し처럼요!", ja: "韓国語のㅅは通常「s」ですが、이/야/여 etc. の前では「sh」になります。日本語のし（shi）と似ています！" },
  { en: "Korean has tense (fortis) consonants ㄲ, ㄸ, ㅃ, ㅆ, ㅉ that Japanese lacks — this is often the hardest part for Japanese speakers.", ko: "한국어에는 된소리(ㄲ, ㄸ, ㅃ, ㅆ, ㅉ)가 있는데 일본어에는 없어요. 일본인이 가장 어려워하는 부분이에요!", ja: "韓国語には濃音（ㄲ, ㄸ, ㅃ, ㅆ, ㅉ）がありますが、日本語にはありません。日本人が最も難しいと感じる点です！" },
  { en: "Korean also has aspirated consonants ㅋ, ㅌ, ㅍ, ㅊ — Japanese doesn't distinguish aspirated vs unaspirated in the same way.", ko: "한국어는 격음(ㅋ, ㅌ, ㅍ, ㅊ)도 있어요. 일본어는 유기음/무기음 구별이 없어요.", ja: "韓国語には激音（ㅋ, ㅌ, ㅍ, ㅊ）もあります。日本語には有気音・無気音の区別がありません。" },
  { en: "Japanese pitch accent (高低アクセント) is very different from Korean, which has minimal pitch accent in standard Seoul dialect.", ko: "일본어는 높낮이 악센트(高低アクセント)가 중요해요. 표준 서울말에는 음고 악센트가 거의 없어요.", ja: "日本語の高低アクセントは重要ですが、標準ソウル語にはほぼピッチアクセントがありません。" },
  { en: "The Japanese mora (拍) system means each syllable takes equal time — Korean syllable timing is more flexible.", ko: "일본어의 모라(拍) 체계에서는 각 음절이 같은 시간을 차지해요. 한국어는 좀 더 자유로워요.", ja: "日本語のモーラ（拍）体系では各音節が等時間を占めます。韓国語はより柔軟です。" },
  { en: "Korean 받침 (final consonants) have no equivalent in standard Japanese — words ending in consonants are challenging for Japanese learners.", ko: "한국어 받침(종성)은 일본어에 없는 개념이에요. 받침으로 끝나는 단어가 일본인에게 어려워요.", ja: "韓国語の받침（終声）は日本語にない概念です。子音で終わる単語は日本語話者には難しいです。" },
  { en: "The Korean 'r/l' (ㄹ) sound appears between vowels as a flap [ɾ], similar to Japanese ら行 (r-row) sounds.", ko: "한국어 ㄹ이 모음 사이에서 'ɾ' (탄음)로 발음되는 것은 일본어 ら행 발음과 비슷해요!", ja: "韓国語のㄹが母音間で「ɾ」（弾き音）になるのは、日本語のら行の音と似ています！" },
  { en: "Both Korean 아/야 and Japanese あ/や series show similar vowel harmony patterns in classical texts and children's songs.", ko: "한국어 아/야 계열과 일본어 あ/や 계열은 고전 문헌과 동요에서 비슷한 모음 조화 패턴을 보여요.", ja: "韓国語のア/ヤ系列と日本語のあ/や系列は、古典文献や童謡で似た母音調和パターンを示します。" },
  { en: "Korean loanword phonology often changes 'f' sounds to 'p': 파일 (pa-il = file), 포크 (po-keu = fork) — Japanese does the same: ファイル, フォーク.", ko: "한국어는 f를 p로 바꿔요: 파일(file), 포크(fork). 일본어도 마찬가지: ファイル, フォーク!", ja: "韓国語はfをpに変えます：파일（file）、포크（fork）。日本語も同様：ファイル、フォーク！" },
  { en: "Both languages struggle with the English 'v' sound — Korean uses ㅂ and Japanese uses バ行, both approximating 'v' as 'b'.", ko: "두 언어 모두 영어 v 발음이 어려워요. 한국어는 ㅂ, 일본어는 バ行으로 v를 b처럼 발음해요.", ja: "両言語とも英語のv音が難しいです。韓国語はㅂ、日本語はバ行でvをbのように発音します。" },
  { en: "Korean double vowels like 외 (oe) and 위 (wi) are being simplified in modern speech — similar simplification happened in historical Japanese.", ko: "현대 한국어에서 외(oe)와 위(wi)가 단순화되는 것은 역사적으로 일본어에서도 일어난 변화와 비슷해요.", ja: "現代韓国語で외（oe）と위（wi）が単純化されているのは、歴史的に日本語で起きた変化と似ています。" },
  { en: "The Korean alphabet Hangul has letters that cluster into syllable blocks — 가 = ㄱ+ㅏ. Japanese hiragana/katakana has one character per syllable, like か.", ko: "한글은 자음+모음을 모아쓰기 해요. 가=ㄱ+ㅏ처럼요. 일본어 가나는 음절당 한 글자예요.", ja: "ハングルは子音＋母音を組み合わせて書きます。가＝ㄱ＋ㅏのように。日本語の仮名は音節ごとに一文字です。" },
  { en: "Hangul was invented in 1443 by King Sejong to increase literacy. Before that, Koreans also used Chinese characters (hanja) like Japan still does.", ko: "한글은 1443년 세종대왕이 만들었어요. 그 전에는 한국도 일본처럼 한자만 사용했어요.", ja: "ハングルは1443年に世宗大王が発明しました。それ以前、韓国も日本と同様に漢字のみを使っていました。" },
  { en: "Japanese has THREE writing systems: hiragana (ひらがな) for grammar, katakana (カタカナ) for loanwords, and kanji (漢字) — used together in a single sentence!", ko: "일본어는 세 가지 문자를 써요: 히라가나(문법), 가타카나(외래어), 한자 — 한 문장 안에 함께 사용해요!", ja: "日本語は三種の文字を使います：ひらがな（文法）、カタカナ（外来語）、漢字 — 一文中に混在します！" },
  { en: "Korean uses Hangul exclusively now (hanja is rarely used), while Japanese still uses all three systems daily. Different evolution paths!", ko: "현대 한국어는 한글만 사용해요(한자는 드물어요). 일본어는 아직도 세 문자를 매일 써요!", ja: "現代韓국語はハングルのみ使用（漢字は稀）。日本語は今も三種の文字を毎日使います！" },
  { en: "Both Korean ㅎ and Japanese は (ha) have undergone historical sound changes — both were once pronounced differently in ancient texts.", ko: "한국어 ㅎ와 일본어 は는 모두 고대에는 다르게 발음되었어요. 언어는 시간에 따라 변해요!", ja: "韓国語のㅎと日本語のははどちらも古代には異なる発音でした。言語は時とともに変化します！" },
  { en: "Korean syllable structure allows for consonant clusters in codas that Japanese doesn't: 읽다 (ilk-da = to read) would be impossible in Japanese phonology.", ko: "한국어는 받침에 자음군이 올 수 있어요. 읽다의 'ㄺ'처럼요. 일본어에는 이런 구조가 없어요.", ja: "韓国語は末尾に子音群を持てます。읽다の「ㄺ」のように。日本語にはこのような構造はありません。" },
  { en: "Both Korean and Japanese nasals (ㄴ, ㅁ / ん, m-before-b) assimilate to following sounds — phonological rules work similarly.", ko: "두 언어 모두 비음(ㄴ, ㅁ / ん)이 뒤따르는 소리에 동화되는 규칙이 있어요.", ja: "両言語とも鼻音（ㄴ, ㅁ / ん）が後続音に同化するルールがあります。" },
  { en: "The Korean vowel ㅡ (eu) has no Japanese equivalent — it's the most challenging Korean vowel for Japanese speakers to pronounce.", ko: "한국어 ㅡ(으) 모음은 일본어에 없어요. 일본인이 가장 발음하기 어려운 모음이에요!", ja: "韓国語の母音ㅡ（으）は日本語にありません。日本人が最も発音しにくい母音です！" },

  // 401-450: False friends / tricky words
  { en: "Korean 편지 (pyeon-ji) means 'letter (mail)', not related to Japanese 便器 (benki = toilet). Same hanja 便 but totally different meanings!", ko: "한국어 편지(便紙 = 편지)와 일본어 便器(べんき = 변기)는 같은 한자 便을 쓰지만 뜻이 완전 달라요!", ja: "韓국語의편지（手紙）と日本語の便器（べんき）は同じ漢字「便」を使いますが、まったく違う意味です！" },
  { en: "Korean 수업 (su-eop) means 'class/lesson'. Japanese 授業 (jugyō) also means 'class'. These ARE the same! But don't confuse with 수업료 (tuition) vs 月謝 (gessha).", ko: "수업과 授業는 둘 다 '수업'이에요. 하지만 수업료(수업비)는 한국어, 月謝(げっしゃ)는 일본어 학원비 표현이에요.", ja: "수업と授業はどちらも「授業」です。でも학원비は韓국語、月謝（げっしゃ）は日本語の塾代表現です。" },
  { en: "Korean 도로 (do-ro) means 'road/street'. Japanese 道路 (dōro) means the same! These match perfectly — same hanja 道路.", ko: "도로(道路)와 日本語 道路(どうろ)는 둘 다 '길'이에요. 한자도 뜻도 같아요!", ja: "도로（道路）と道路（どうろ）はどちらも「道路」です。漢字も意味も同じです！" },
  { en: "Korean 감동 (gam-dong) means 'being moved/touched'. Japanese 感動 (kandō) means the same! They share 感動 perfectly.", ko: "감동(感動)과 感動(かんどう)는 둘 다 '깊이 감동받은 상태'예요. 완벽하게 일치해요!", ja: "감동（感動）と感動（かんどう）はどちらも「深く感動した状態」を意味します。完全に一致！" },
  { en: "Korean 유명 (yu-myeong) means 'famous'. Japanese 有名 (yūmei) means the same. These match! But note: Korean 무명 (mu-myeong) = 'unknown', Japanese 無名 (mumei) = same!", ko: "유명(有名)=有名(ゆうめい) '유명한', 무명(無名)=無名(むめい) '무명의'. 한자 구조가 완전히 같아요!", ja: "유명（有名）＝有名（ゆうめい）「有名な」、무명（無名）＝無名（むめい）「無名の」。漢字構造が完全に一致！" },
  { en: "Korean 인기 (in-gi) means 'popularity'. Japanese 人気 (ninkī) means the same! 인기 있다 = 人気がある = 'to be popular'.", ko: "인기(人気)와 人気(にんき)는 둘 다 '인기'예요. 인기 있다=人気がある, 완전히 같은 표현이에요!", ja: "인기（人気）と人気（にんき）はどちらも「人気」です。인기 있다＝人気がある、まったく同じ表現です！" },
  { en: "Korean 기분 (gi-bun) means 'mood/feeling'. Japanese 気分 (kibun) means the same — 기분이 좋다/気分がいい = 'feeling good'.", ko: "기분(気分)과 気分(きぶん)는 둘 다 '기분'이에요. 기분이 좋다=気分がいい, 완전히 같아요!", ja: "기분（気分）と気分（きぶん）はどちらも「気分」です。기분이 좋다＝気分がいい、完全に一致！" },
  { en: "Korean 연락 (yeol-lak) means 'contact/communication'. Japanese 連絡 (renraku) means the same — 연락해줘/連絡してね = 'contact me'.", ko: "연락(連絡)과 連絡(れんらく)는 완전히 같은 뜻이에요. 연락해줘=連絡してね!", ja: "연락（連絡）と連絡（れんらく）は完全に同じ意味です。연락해줘＝連絡してね！" },
  { en: "A tricky one: Korean 사고 (sa-go) can mean 'accident' (事故) or 'thinking/thought' (思考). Japanese 事故 (jiko) = accident, 思考 (shikō) = thinking — context matters!", ko: "한국어 사고는 事故(사고, 사건)와 思考(사고, 생각) 두 가지 뜻이에요. 일본어도 각각 事故(じこ)/思考(しこう)로 구별해요!", ja: "韓국語의 사고は事故（事故）と思考（思考）の二つの意味があります。日本語では事故（じこ）/思考（しこう）と区別します！" },
  { en: "Korean 의미 (ui-mi) = Japanese 意味 (imi) = 'meaning'. These are near-identical in sound and completely identical in meaning!", ko: "의미(意味)와 意味(いみ)는 발음도 비슷하고 뜻도 완전히 같아요! 두 언어를 배울 때 정말 도움이 돼요!", ja: "의미（意味）と意味（いみ）は発音も似ていて意味もまったく同じ！両言語を学ぶ時にとても役立ちます！" },
  { en: "Korean 주의 (ju-ui) = Japanese 注意 (chūi) = 'caution/attention'. Both use the same concept and characters!", ko: "주의(注意)와 注意(ちゅうい)는 둘 다 '조심/주의'예요. 한자와 뜻이 같아요.", ja: "주의（注意）と注意（ちゅうい）はどちらも「注意」です。漢字も意味も同じです。" },
  { en: "Korean 자유 (ja-yu) = Japanese 自由 (jiyū) = 'freedom'. One of the many exact matches between these languages!", ko: "자유(自由)와 自由(じゆう)는 둘 다 '자유'예요. 두 언어의 완벽한 일치 예시 중 하나예요!", ja: "자유（自由）と自由（じゆう）はどちらも「自由」です。両言語の完璧な一致例のひとつです！" },
  { en: "Korean 평화 (pyeong-hwa) = Japanese 平和 (heiwa) = 'peace'. Different pronunciation, same meaning and characters.", ko: "평화(平和)와 平和(へいわ)는 발음은 달라도 한자도 뜻도 같아요.", ja: "평화（平和）と平和（へいわ）は発音は違いますが、漢字も意味も同じです。" },
  { en: "Korean 행복 (haeng-bok) = Japanese 幸福 (kōfuku) = 'happiness'. Both from 幸福 — learning one helps you guess the other!", ko: "행복(幸福)과 幸福(こうふく)는 둘 다 '행복'이에요. 하나를 알면 다른 것도 추측할 수 있어요!", ja: "행복（幸福）と幸福（こうふく）はどちらも「幸福」です。一方を知ればもう一方も推測できます！" },
  { en: "Korean 영원 (yeong-won) = Japanese 永遠 (eien) = 'eternity/forever'. Both from 永遠 — classic in love songs in both languages!", ko: "영원(永遠)과 永遠(えいえん)는 둘 다 '영원'이에요. 두 나라 러브송에 많이 등장하는 단어예요!", ja: "영원（永遠）と永遠（えいえん）はどちらも「永遠」。両国のラブソングによく登場する言葉です！" },
  { en: "Korean 기억 (gi-eok) = Japanese 記憶 (kioku) = 'memory'. Different sound but same characters and meaning!", ko: "기억(記憶)과 記憶(きおく)는 발음이 달라도 한자도 뜻도 같아요.", ja: "기억（記憶）と記憶（きおく）は発音は違いますが、漢字も意味も同じです。" },
  { en: "Korean 희망 (hui-mang) = Japanese 希望 (kibō) = 'hope'. Both elegant words for the same beautiful concept.", ko: "희망(希望)과 希望(きぼう)는 둘 다 '희망'이에요. 아름다운 개념에 대한 우아한 단어들이에요.", ja: "희망（希望）と希望（きぼう）はどちらも「希望」です。美しい概念を表す品のある言葉です。" },
  { en: "Korean 꿈 (kkum) and Japanese 夢 (yume) both mean 'dream' — completely different words, but this is the native word in each language.", ko: "꿈과 夢(ゆめ)는 둘 다 '꿈'이에요. 완전히 다른 고유어지만 같은 아름다운 개념이에요.", ja: "꿈と夢（ゆめ）はどちらも「夢」。まったく異なる固有語ですが、同じ美しい概念です。" },
  { en: "Korean 사랑 (sa-rang) and Japanese 愛 (ai) or 恋 (koi) both express 'love' — Korean uses a native word while Japanese has two: 愛 (deeper love) and 恋 (romantic longing).", ko: "한국어 사랑은 고유어예요. 일본어는 愛(あい, 깊은 사랑)와 恋(こい, 연애 감정)를 구별해요!", ja: "韓国語の사랑は固有語。日本語は愛（あい、深い愛）と恋（こい、恋愛感情）を区別します！" },
  { en: "Korean 맛있다 (ma-sit-da) means 'delicious'. Japanese おいしい (oishii) or 美味しい also means 'delicious' — completely different words for the same joy!", ko: "맛있다와 おいしい는 완전히 다른 단어지만 같은 기쁨(맛있음)을 표현해요!", ja: "맛있다とおいしいはまったく異なる言葉ですが、同じ喜び（おいしさ）を表現します！" },

  // 451-500: Writing system facts, historical connections
  { en: "Chinese characters (漢字/한자) were introduced to both Korea and Japan from China — Korea around the 4th century, Japan slightly later via Korea.", ko: "한자는 한국에는 4세기경, 일본에는 한국을 통해 전해졌어요. 두 나라 문화의 공통 뿌리예요!", ja: "漢字は韓国には4世紀頃、日本には韓国を経由して伝わりました。両国文化の共通の根です！" },
  { en: "Buddhism spread to both Korea and Japan from China, bringing with it many Chinese Buddhist terms that both languages still use today.", ko: "불교는 중국에서 두 나라에 전해졌고, 많은 불교 한자어를 함께 가져왔어요. 지금도 많이 쓰여요.", ja: "仏教は中国から両国に伝わり、多くの仏教漢字語を持ち込みました。今も広く使われています。" },
  { en: "The Meiji-era Japanese coined many new Chinese character compounds for Western concepts — and Korea borrowed many of these directly! Words like 철학 (philosophy), 경제 (economy) were Japanese inventions.", ko: "메이지 시대 일본이 서양 개념을 한자어로 만들었고, 한국이 그 단어들을 많이 차용했어요! 철학, 경제 등이 그 예예요.", ja: "明治時代の日本が西洋概念を漢字語で作り、韓国がそれらを多く借用しました！哲学・経済などがその例です。" },
  { en: "Korean hanja (한자) and Japanese kanji (漢字) are the same characters, but Korean readings are often different from both Chinese and Japanese readings.", ko: "한자(漢字)는 같은 글자지만 한국어 발음, 일본어 발음, 중국어 발음이 모두 달라요. 같은 글자, 세 나라 발음!", ja: "漢字は同じ文字ですが、韓国語読み・日本語読み・中国語読みがすべて異なります。同じ文字、三国の読み方！" },
  { en: "Japanese kanji have two types of readings: 音読み (on-yomi, Chinese origin) and 訓読み (kun-yomi, Japanese native). Korean hanja only have one reading each.", ko: "일본 한자는 音読み(한자음)와 訓読み(순일본어 읽기) 두 가지가 있어요. 한국 한자는 보통 한 가지 읽기만 있어요.", ja: "日本の漢字は音読み（中国語起源）と訓読み（日本固有語）の二種類があります。韓国の漢字は通常一つの読みです。" },
  { en: "The Chinese character for 'person' (人) is read 인 (in) in Korean and 人 (jin/nin/hito) in Japanese — multiple readings in Japanese, single in Korean.", ko: "人자는 한국어로 '인'(사람인), 일본어로는 じん/にん(음독)이나 ひと(훈독)으로 읽어요.", ja: "「人」という漢字は韓국語で「인」、日本語ではじん/にん（音読み）またはひと（訓読み）と読みます。" },
  { en: "The character 水 (water) is 수 (su) in Korean, 水 (mizu/sui) in Japanese — 수영 (swimming) and 水泳 (suiei) both use this character!", ko: "水자는 한국어로 '수', 일본어로 みず(훈독)/すい(음독). 수영=水泳(すいえい) 둘 다 같은 한자예요!", ja: "「水」の漢字は韓国語で「수」、日本語でみず（訓読み）/すい（音読み）。수영＝水泳（すいえい）で同じ漢字！" },
  { en: "Korean and Japanese share the same stroke order rules for Chinese characters — learned from the same Chinese calligraphy tradition.", ko: "한국어와 일본어 한자 획순은 같은 중국 서예 전통에서 왔어요. 쓰는 순서가 같아요!", ja: "韓国語と日本語の漢字の筆順は同じ中国書道の伝統から来ています。書く順序が同じです！" },
  { en: "The concept of onyomi/kunyomi (음독/훈독) exists because both Japan and Korea distinguished between borrowed Chinese sound and native meaning.", ko: "음독/훈독 개념은 한국과 일본 모두 중국 발음과 자국어 의미를 구별했기 때문에 생겼어요.", ja: "音読み/訓読みの概念は、韓国も日本も中国語の発音と自国語の意味を区別したため生まれました。" },
  { en: "Katakana was derived from parts of Chinese characters in the 9th century. Hangul was invented from scratch in 1443 — two different approaches to writing!", ko: "가타카나는 9세기에 한자의 일부에서 만들어졌고, 한글은 1443년에 처음부터 창제되었어요. 두 가지 다른 접근법!", ja: "カタカナは9世紀に漢字の一部から作られ、ハングルは1443年にゼロから創案されました。二つの異なるアプローチ！" },
  { en: "Hiragana was developed by simplifying Chinese cursive script — a natural evolution over centuries, unlike Hangul's deliberate invention.", ko: "히라가나는 한자 초서체를 간략화해서 자연스럽게 발전했어요. 한글의 의도적 창제와는 다른 과정이에요.", ja: "ひらがなは漢字の草書体を簡略化して自然に発展しました。ハングルの意図的な創案とは異なる過程です。" },
  { en: "Both Korea and Japan were significant trading partners for centuries — cultural exchange included not just language but art, music, food, and religion.", ko: "한국과 일본은 수백 년간 중요한 무역 파트너였어요. 언어뿐 아니라 예술, 음악, 음식, 종교도 교류했어요.", ja: "韓国と日本は数百年にわたる重要な貿易パートナーでした。言語だけでなく芸術・音楽・食・宗教も交流しました。" },
  { en: "The Korean kingdom of Baekje sent scholars, artists, and craftspeople to Japan in the 5th-7th centuries — direct cultural transfer!", ko: "백제는 5-7세기에 학자, 예술가, 장인을 일본에 보냈어요. 직접적인 문화 전달이었어요!", ja: "百済は5〜7世紀に学者・芸術家・職人を日本に送りました。直接的な文化の移転でした！" },
  { en: "The first Japanese writing system was based on Chinese characters, adapted phonetically — similar to how early Korean hyangchal (향찰) worked.", ko: "일본 최초 문자도 한자를 음차한 것이었어요. 한국의 초기 향찰 표기법과 비슷한 방식이에요!", ja: "日本最初の文字も漢字を音借りしたものでした。韓国の初期の郷札（향찰）表記法と似た方式です！" },
  { en: "Both countries have a long tradition of poetry: Korean 시조 (sijo) and Japanese 俳句 (haiku) / 短歌 (tanka) are short-form poetic traditions.", ko: "두 나라 모두 시 전통이 깊어요. 한국의 시조와 일본의 俳句(하이쿠)/短歌(단카)는 짧은 시 형식이에요.", ja: "両国とも詩の伝統が深いです。韓国の시조と日본の俳句・短歌はどちらも短詩形の伝統です。" },
  { en: "Modern Korean and Japanese both absorbed enormous numbers of English loanwords after WWII — both languages are still evolving rapidly.", ko: "현대 한국어와 일본어는 2차 세계대전 이후 엄청난 수의 영어 외래어를 흡수했어요. 두 언어 모두 빠르게 변화 중이에요.", ja: "現代韓国語と日本語はどちらも第二次世界大戦後に膨大な英語借用語を吸収しました。両言語は今も急速に進化中です。" },
  { en: "Both Korean and Japanese internet slang evolves rapidly and shares memes — ㅋㅋ (Korean laughing) and www (Japanese laughing, from 笑い warai) are digital-age parallels.", ko: "한국어 ㅋㅋ(웃음)와 일본어 www(笑い에서)는 둘 다 인터넷 웃음 표현이에요. 디지털 시대의 평행 문화!", ja: "韓국語のㅋㅋ（笑い）と日本語のwww（笑い＝waraiから）はどちもネット上の笑い表現。デジタル時代の並行文化！" },
  { en: "The honorific suffix -님 (-nim) in Korean and -さん (-san) in Japanese both add respect to names/titles — 선생님/先生さん are polite ways to address teachers.", ko: "-님(한국어)과 -さん(일본어)는 둘 다 존칭 접미사예요. 선생님과 先生さん처럼요.", ja: "韓国語の-님と日本語の-さんはどちらも敬称サフィックスです。선생님と先生さんのように。" },
  { en: "Korean 오빠 (oppa) for older brother (said by girls) and Japanese お兄さん (oniisan) — both cultures have specific terms for older vs younger siblings!", ko: "한국의 오빠/언니/형/누나와 일본의 お兄さん/お姉さん처럼, 두 나라 모두 형제자매를 나이로 구별해요!", ja: "韓국語の오빠/언니/형/누나と日本語のお兄さん/お姉さんのように、両国とも兄弟姉妹を年齢で区別します！" },
  { en: "Both Korean and Japanese have unique words for 'older sister of a girl' (언니/お姉さん), 'older sister of a boy' (누나), 'older brother of a girl' (오빠), and 'older brother of a boy' (형).", ko: "한국어에는 오빠/형/언니/누나가 있고, 일본어는 お兄さん/お姉さん로 성별을 덜 구별해요. 한국어가 더 세분화돼요!", ja: "韓国語には오빠/형/언니/누나があり、日本語はお兄さん/お姉さんと性別をあまり区別しません。韓国語の方が細分化されています！" },
  { en: "Both languages have humble and respectful speech: Korean 저 (humble 'I') vs 나 (plain 'I'), and Japanese 私 (watashi) vs 俺 (ore) vs 僕 (boku).", ko: "한국어 저(겸손)/나(평어), 일본어 私/俺/僕처럼 두 언어 모두 화자의 자기 호칭이 여러 가지예요!", ja: "韓国語の저（謙虚）/나（普通）、日本語の私/俺/僕のように、両言語とも自分の呼び方が複数あります！" },
  { en: "The ending 입니다 (im-ni-da) in Korean and です (desu) in Japanese are both formal sentence-ending copulas — 'am/is/are' in polite form.", ko: "한국어 입니다와 일본어 です는 둘 다 정중한 서술어 종결어미예요. 둘 다 '~입니다/~이다'의 공손한 형태예요.", ja: "韓国語의입니다と日本語のですはどちらも丁寧な文末の断定助動詞です。どちらも「〜です」の丁寧形です。" },
  { en: "Learning Korean makes Japanese vocabulary much easier — about 60% of Korean vocabulary has Chinese character roots, and so does much of Japanese!", ko: "한국어를 배우면 일본어 어휘가 훨씬 쉬워져요! 한국어의 약 60%가 한자어이고, 일본어도 그래요!", ja: "韓国語を学ぶと日本語の語彙がずっと簡単になります！韓国語の約60%は漢字語で、日本語も同様です！" },
  { en: "Conversely, learning Japanese makes Korean much more accessible — the grammar structures are so similar that if you know one, you're halfway to the other!", ko: "반대로, 일본어를 배우면 한국어가 훨씬 쉬워져요. 문법 구조가 너무 비슷해서 하나를 알면 반은 아는 셈이에요!", ja: "逆に、日本語を学べば韓国語がずっとアクセスしやすくなります。文法構造が非常に似ているので、一方を知れば半分はわかったも同然です！" },
  { en: "The mutual intelligibility between Korean and Japanese is low in spoken form, but the huge shared vocabulary from Chinese characters creates a 'visual bridge' in writing.", ko: "한국어와 일본어는 구어 상호이해도는 낮지만, 한자 어휘라는 '시각적 다리'가 쓰기에서 연결해줘요!", ja: "韓国語と日本語は口頭での相互理解度は低いですが、漢字語彙という「視覚的な橋」が文字で両言語をつなぎます！" },
  { en: "Studying Korean-Japanese connections is not just linguistic — it's a window into shared East Asian history, philosophy, art, and human connection across cultures.", ko: "한국어-일본어 연결을 공부하는 것은 단순한 언어학이 아니에요. 동아시아의 역사, 철학, 예술, 문화 간 인간적 연결의 창문이에요!", ja: "韓国語と日本語のつながりを学ぶのは単なる言語学ではありません。東アジアの歴史・哲学・芸術・文化を超えた人間的なつながりへの窓です！" },
];
